version: '3.1'

networks:
  database:

services:
  api:
    container_name: api
    build: .
    ports:
      - 8081:8081
    networks:
      - database
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0.8
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=root"
      - "MONGO_INITDB_ROOT_PASSWORD=test"
    networks:
      - database
