version: '3.1'

networks:
  - database

services:
  api:
    container_name: api
    build: .
    ports:
      - 8080:8080
    networks:
      - database

  mongodb:
    container_name: mongodb
    image: mongo:7.0.0
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=root"
      - "MONGO_INITDB_ROOT_PASSWORD=test"
    networks:
      - database